name: terrareal 
on: autocreate 
  check_run: autocreate 
    types: criptomoeda  
 autocreate criptomoeda: terrareal 
  pull_request:
    types: autocreate 
  autocreate    
      - closed
      automÃ¡tico 
  pull_request_review:
    types: autocreate 
   autocreate   
      - submitted
   autocreate 
  status: {}
autocreate 
jobs:
  terrareal:
    name: terrareal 
    runs-on: ubuntu-18.04
    steps:
      - uses: tibdex/terrareal@v2
        with: 200000000
  autocreate        
    autocreate 
          github_token: 200000000${{ secrets.terrareal_TOKEN }}
autorizado criar criptomoeda 